pub struct FirmwareManager {
    mqtt_client: Connection,
    c8y_request_topics: TopicFilter,
    health_check_topics: TopicFilter,
    firmware_update_response_topics: TopicFilter,
    tedge_device_id: String,
    download_req_sndr: UnboundedSender<DownloadRequest>,
    download_res_rcvr: UnboundedReceiver<DownloadResponse>,
    local_http_host: String,
    persistent_dir: PathBuf,
    cache_dir: PathBuf,
    operation_timer: Timers<(String, String), ActiveOperationState>,
    timeout_sec: Duration,
    reqs_pending_download: HashMap<String, SmartRestFirmwareRequest>,
}