[package]
name = "tedge-agent"
description = "tedge-agent interacts with a Cloud Mapper and one or more Software Plugins"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[package.metadata.deb]
pre-depends = "tedge-mapper"
replaces = "tedge_agent"
conflicts = "tedge_agent (<= 0.8.1)"
breaks = "tedge_agent (<= 0.8.1)"
provides = "tedge_agent"
maintainer-scripts = "../../../configuration/debian/tedge-agent"
assets = [
    [
        "../../../configuration/init/systemd/tedge-agent.service",
        "/lib/systemd/system/tedge-agent.service",
        "644",
    ],
    [
        "target/release/tedge-agent",
        "/usr/bin/tedge-agent",
        "755",
    ],
]
# Contrary to the other daemons,
# The `agent` does not use `systemd-units` of `cargo-deb`:
# for OTA self-update one needs a fine-control over the deb options

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
camino = "1.1.4"
clap = { version = "3.2", features = ["cargo", "derive"] }
flockfile = { path = "../../common/flockfile" }
futures = "0.3"
futures-util = "0.3"
hyper = { version = "0.14", features = ["full"] }
lazy_static = "1.4"
mqtt_channel = { path = "../../common/mqtt_channel" }
path-clean = "0.1"
plugin_sm = { path = "../plugin_sm" }
routerify = "3.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tedge_api = { path = "../../core/tedge_api" }
tedge_config = { path = "../../common/tedge_config" }
tedge_utils = { path = "../../common/tedge_utils", features = ["logging"] }
tedge_mqtt_ext = { path = "../../extensions/tedge_mqtt_ext" }
thiserror = "1.0"
time = { version = "0.3", features = ["formatting"] }
tokio = { version = "1.23", features = [
    "fs",
    "process",
    "rt",
    "rt-multi-thread",
] }
toml = "0.5"
tracing = { version = "0.1", features = ["attributes", "log"] }
# from here for actors
tedge_actors = { path = "../../core/tedge_actors" }
tedge_signal_ext = { path = "../../extensions/tedge_signal_ext" }

[dev-dependencies]
anyhow = "1.0"
assert-json-diff = "2.0"
assert_cmd = "2.0"
async-stream = "0.3"
mqtt_tests = { path = "../../tests/mqtt_tests" }
once_cell = "1.8"
predicates = "2.1"
serial_test = "0.8"
tedge_actors = { path = "../../core/tedge_actors" }
tedge_api = { path = "../../../crates/core/tedge_api" }
tedge_config = { path = "../../../crates/common/tedge_config" }
tedge_downloader_ext = { path = "../../extensions/tedge_downloader_ext" }
tedge_timer_ext = { path = "../../extensions/tedge_timer_ext" }
tedge_utils = { path = "../../../crates/common/tedge_utils" }
tedge_test_utils = { path = "../../tests/tedge_test_utils" }
test-case = "2.2"
tokio-test = "0.4"
toml = "0.5"
