[package]
name = "tedge_gen_mapper"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
camino = { workspace = true, features = ["serde1"] }
rquickjs = { workspace = true, default-features = false, features = [
    "futures",
    "parallel",
] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tedge_actors = { workspace = true }
tedge_file_system_ext = { workspace = true }
tedge_mqtt_ext = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tokio = { workspace = true, features = ["fs", "macros", "time", "sync"] }
toml = { workspace = true, features = ["parse"] }
tracing = { workspace = true }

[lints]
workspace = true
