[package]
name = "tedge-mapper"
description = "tedge-mapper translates thin-edge.io data model to c8y/az/aws data model"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
aws_mapper_ext = { workspace = true, optional = true }
az_mapper_ext = { workspace = true, optional = true }
batcher = { workspace = true }
c8y_api = { workspace = true, optional = true }
c8y_auth_proxy = { workspace = true, optional = true }
c8y_mapper_ext = { workspace = true, optional = true }
clap = { workspace = true }
clock = { workspace = true }
collectd_ext = { workspace = true }
flockfile = { workspace = true }
mqtt_channel = { workspace = true }
tedge_actors = { workspace = true }
tedge_api = { workspace = true }
tedge_config = { workspace = true }
tedge_downloader_ext = { workspace = true }
tedge_file_system_ext = { workspace = true }
tedge_gen_mapper = { workspace = true }
tedge_health_ext = { workspace = true }
tedge_http_ext = { workspace = true }
tedge_mqtt_bridge = { workspace = true }
tedge_mqtt_ext = { workspace = true }
tedge_signal_ext = { workspace = true }
tedge_timer_ext = { workspace = true }
tedge_uploader_ext = { workspace = true }
tracing = { workspace = true }
yansi = { workspace = true }

[features]
default = ["aws", "azure", "c8y"]
aws = ["dep:aws_mapper_ext"]
azure = ["dep:az_mapper_ext"]
c8y = ["dep:c8y_mapper_ext", "dep:c8y_api", "dep:c8y_auth_proxy"]
integration-test = []

[lints]
workspace = true
