# This flow is on purpose looping: the messages are published to the same topic
input_topics = ["loopback/#"]

stages = [
    { filter = "add_timestamp.js" },
    { filter = "circuit-breaker.js", tick_every_seconds = 1, config = { stats_topic = "te/error", too_many = 10000, message_on_too_many = { topic = "te/device/main///a/too-many-messages", payload = "too many messages" }, message_on_back_to_normal = { topic = "te/device/main///a/too-many-messages", payload = "back to normal" } } }
]
